### ISSUE TITLE
EPIC - Filmer

### ISSUE THREAD

**Issue by SpinalGlitter** [Nishune/Kino_Group_Project#59]
### **USER**
Som en användare vill jag kunna se en lista över filmer så att jag enkelt kan hitta och få relevant information om filmerna som visas i listan.

**Feature:** Visa lista med filmer.

### **BDD**

Given att jag befinner mig på filmsidan
When jag laddar sidan
Then ska jag se en lista över tillgängliga filmer
And varje film ska visa titel och genre.

**Tasks**
- [x] #9 - Skapa JSON-fil med data för sektionen filmer.
- [x] #10 - Skapa strukturen för HTML.
- [x] #15 - Ladda data från JSON-fil.
- [x] #20 - Bygga DOM:en med Javascript.
- [x] #24 - Designa en mobil-vy för "filmer sektionen" utifrån stylingen på Figma.
