### ISSUE TITLE
EPIC - Header

### ISSUE THREAD

**Issue by Nishune** [Nishune/Kino_Group_Project#60]
### User 

Som en användare vill jag kunna besöka sidan, och se en användarvänlig och snygg navigationsmeny som enkelt kan navigera mig till innehåll på sidan som jag är intresserad utav.

### BDD

Given: Användaren är på någon av våra sidor.
When: När användaren ser navigationsmenyn.
Then: Ska användaren direkt kunna känna igen sig i hur denna fungerar och navigera till det länkar som finns i navigationmenyn. I detta fall "Logotyp-texten" som tar användaren till startsidan, "Barnkalas" tar användaren till barnkalas-sidan och "Om oss" tar användaren till Om oss-sidan.

### Tasks

- [x] #5 - Skapa JSON fil med data för Header.
- [x] #11 - Skapa en HTML struktur som är redo för att sedan bygga DOM med Javascript.
- [x] #22 - Fetcha API och göra data redo att arbeta med i Javascript.
- [x] #19 - Bygg upp DOM strukturen med hjälp av data från JSON samt designen på Figma.
- [x] #23 - Skapa styling för Header utefter designen på Figma mobile style.

### Bilder på design från figma samt länk

Design för mobilvy:

![Image](https://github.com/user-attachments/assets/d3d07d01-d319-4c9c-8ca9-e7e811d48840)

När användare klickar på hamburgermenyn:

![Image](https://github.com/user-attachments/assets/89ee0d93-0c2e-4a22-9c4d-4b0628e65e08)

Design för desktop vy:

![Image](https://github.com/user-attachments/assets/1df7db23-9180-4c6b-9c95-d07270d36f03)

**Länk till Figma: https://www.figma.com/design/NgPXnZYcrnaG2BB4L8CprR/Biograf-sajt?node-id=0-1&p=f&t=gbqV3QiqzGAzxKmX-0**

### Typ

Del av Feature
