### ISSUE TITLE
EPIC - Informationsmodal

### ISSUE THREAD

**Issue by viktornoskire** [Nishune/Kino_Group_Project#61]
### User story 
Som användare vill jag kunna läsa om information om biografen, som till exempel öppettider och allmän information. 

Som användare med funktionshinder vill jag kunna hitta information om tillgänglighet i biografen. 

### BDD 
- Given: Användaren befinner sig inne på hemsidan, antingen på startsidan eller om oss-sidan.
- When: Användaren vill ta reda på viktig information som tillgänglighet eller öppettider. 
- Then: Användaren klickar på knapparna för att de olika flikarna med text visas med respektive information. Kort om biografen visar till exempel att biografen är kontantfri. Tillgänglighet visar information för folk med funktionshinder. Öppettider visar öppettider för en vecka framåt. 

### Included cards
- [x] #29: Skapar ett JSON-fil för att senare kunna skicka data till DOM.
- [x] #31: Skapar en mall för HTML för att kunna lägga till DOM element från JSON
- [x] #33:  Använder JavaScript för att hämta data från JSON-filen. 
- [x] #32: Använder data från JSON för att bygga DOMen och rendera text med JS. 
- [x] #28: Skapa en fin design för mindre skärmar. 
- [x] #52: Skapa en fin design för större skärmar.

### Mobile info modal
![Image](https://github.com/user-attachments/assets/f7c1ed4b-98ef-4647-a449-bbbb809e2672)

### Desktop info modal
![Image](https://github.com/user-attachments/assets/3c450b83-770e-45c0-b7c6-72b3fe89ddd4)

### Typ 
Feature
